name: hackathon_one
version: 0.0.1
author: Allan MacDonald
description: A sample Polymer application
homepage: https://github.com/iggymacd/hackathon1
dependencies:
  polymer: '>=0.12.0 <0.13.0'
transformers:
- polymer:
    entry_points: web/index.html
